version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Docker/node/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - time-service
      - user-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Docker/node/Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./user-service:/home/node/app
    networks:
      - app-network
    depends_on:
      - user-db

  time-service:
    build:
      context: ./time-service
      dockerfile: Docker/node/Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./time-service:/home/node/app
    networks:
      - app-network
    depends_on:
      - time-db

  time-db:
    image: mongo:latest
    container_name: time-mongo
    ports:
      - "27018:27017"
    volumes:
      - time-db-data:/data/db
    networks:
      - app-network

  user-db:
    image: mongo:latest
    container_name: user-mongo
    ports:
      - "27017:27017"
    volumes:
      - user-db-data:/data/db
    networks:
      - app-network

volumes:
  time-db-data:
  user-db-data:

networks:
  app-network:
    driver: bridge
